[tool.black]
line-length = 79
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  | migrations
  | .venv
  | .git
  | __pycache__
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79
known_first_party = [
  "backend", "users", "education", "subscriptions",
  "progress", "mentoring", "content", "communication"
]
force_single_line = false
force_sort_within_sections = true

[tool.flake8]
max-line-length = 79
ignore = "E203, W503, E501, C901"
exclude = ".git,__pycache__,build,dist,.venv,venv,migrations,alembic"
filename = "*.py"
per-file-ignores = [
  "__init__.py:F401",
  "tests/*:S101"
]
max-complexity = 10

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
