[pytest]
DJANGO_SETTINGS_MODULE = school_platform.settings
python_files = test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
testpaths = content/tests users/tests
norecursedirs = .env .git __pycache__ migrations venv .venv

# Маркеры для категоризации тестов
markers =
    fast: быстрые тесты (юниты)
    slow: медленные тесты (интеграционные)
    smoke: критический минимум

    unit: модульные тесты
    integration: тесты с зависимостями

    models: тестирование моделей
    api: тестирование API
    services: тестирование бизнес-логики
    tasks: тестирование задач

# Настройки вывода
addopts =
    --strict-markers
    --tb=short
    --verbose
    --reuse-db
    --showlocals
    --no-migrations
    -p no:cacheprovider

filterwarnings =
    ignore::DeprecationWarning:httpx
