# Generated by Django 4.2 on 2026-07-25 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Стабильный код, например pro",
                        max_length=32,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="Название"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Срок (дней)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список кодов фич: mentor_chat, solution_video, conference",
                        verbose_name="Фичи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Entitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin_grant", "Выдача админом"),
                            ("purchase", "Покупка"),
                        ],
                        default="admin_grant",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Начало",
                    ),
                ),
                ("ends_at", models.DateTimeField(verbose_name="Окончание")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отозвано"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заметка"
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_entitlements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто выдал",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entitlements",
                        to="subscriptions.plan",
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выдача тарифа",
                "verbose_name_plural": "Выдачи тарифов",
                "ordering": ("-starts_at",),
            },
        ),
        migrations.AddIndex(
            model_name="entitlement",
            index=models.Index(
                fields=["user", "-ends_at"],
                name="subscriptio_user_id_227c73_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entitlement",
            index=models.Index(
                fields=["user", "revoked_at", "-ends_at"],
                name="subscriptio_user_id_a4ffe8_idx",
            ),
        ),
    ]
