# Generated by Django 4.2 on 2026-07-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_seed_pro_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitlement",
            name="expiry_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Напоминание об окончании отправлено",
            ),
        ),
    ]
