# Generated by Django 4.2 on 2026-08-12 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0003_pro_showcase_reminders"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Латиница и цифры, например EGE2026",
                        max_length=32,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Срок Про (дней)"
                    ),
                ),
                (
                    "max_redemptions",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Пусто — без лимита",
                        null=True,
                        verbose_name="Лимит использований",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Действует до"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заметка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создан"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_promo_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterField(
            model_name="entitlement",
            name="source",
            field=models.CharField(
                choices=[
                    ("admin_grant", "Выдача админом"),
                    ("purchase", "Покупка"),
                    ("promo", "Промокод"),
                ],
                default="admin_grant",
                max_length=20,
                verbose_name="Источник",
            ),
        ),
        migrations.CreateModel(
            name="PromoRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Когда"
                    ),
                ),
                (
                    "entitlement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promo_redemptions",
                        to="subscriptions.entitlement",
                        verbose_name="Выдача",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="subscriptions.promocode",
                        verbose_name="Промокод",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_redemptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Использование промокода",
                "verbose_name_plural": "Использования промокодов",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="promoredemption",
            index=models.Index(
                fields=["user", "-created_at"],
                name="subscriptio_user_id_0ecbec_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promoredemption",
            unique_together={("promo", "user")},
        ),
    ]
