# Generated by Django 4.2 on 2025-12-20 02:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="lessontheory",
            options={
                "ordering": ["order_index"],
                "verbose_name": "Theory lesson",
                "verbose_name_plural": "Theory lessons",
            },
        ),
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["order_index"],
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
            },
        ),
        migrations.AlterModelOptions(
            name="technology",
            options={
                "ordering": ["name"],
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses/images/",
                verbose_name="Course cover",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                max_length=200, unique=True, verbose_name="URL address"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="technology",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="content.technology",
                verbose_name="Technologies",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                max_length=200, verbose_name="Course title"
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="content",
            field=models.TextField(verbose_name="Lesson content"),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_theories",
                to="content.module",
                verbose_name="Module",
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="order_index",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Order number",
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="title",
            field=models.CharField(
                max_length=200, verbose_name="Lesson title"
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="content.course",
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(
                blank=True, verbose_name="Module description"
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="module",
            name="order_index",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Order number",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="title",
            field=models.CharField(
                max_length=200, verbose_name="Module title"
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Technology name"
            ),
        ),
    ]
