# Generated by Django 4.2 on 2026-03-09 18:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0002_alter_course_options_alter_lessontheory_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonRadioQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Question title"
                    ),
                ),
                (
                    "question_text",
                    models.TextField(verbose_name="Question text"),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of the correct answer shown after answering",
                        verbose_name="Explanation",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Order number",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of points for correct answer",
                        verbose_name="Points",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons_radio_questions",
                        to="content.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Radio question lesson",
                "verbose_name_plural": "Radio question lessons",
                "ordering": ["order_index"],
                "unique_together": {("module", "order_index")},
            },
        ),
        migrations.CreateModel(
            name="LessonCheckBoxQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Question title"
                    ),
                ),
                (
                    "question_text",
                    models.TextField(verbose_name="Question text"),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of the correct answers shown after answering",
                        verbose_name="Explanation",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Order number",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of points for fully correct answer",
                        verbose_name="Points",
                    ),
                ),
                (
                    "partial_points",
                    models.BooleanField(
                        default=False,
                        help_text="Award partial points for partially correct answers",
                        verbose_name="Partial points",
                    ),
                ),
                (
                    "min_correct_answers",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum number of correct answers required (for validation)",
                        verbose_name="Minimum correct answers",
                    ),
                ),
                (
                    "max_correct_answers",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of correct answers allowed (for validation)",
                        verbose_name="Maximum correct answers",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons_checkbox_questions",
                        to="content.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkbox question lesson",
                "verbose_name_plural": "Checkbox question lessons",
                "ordering": ["order_index"],
                "unique_together": {("module", "order_index")},
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=500, verbose_name="Answer text"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, verbose_name="Is correct answer"
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Order number",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="content.lessonradioquestion",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer option",
                "verbose_name_plural": "Answer options",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="CheckBoxAnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=500, verbose_name="Answer text"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, verbose_name="Is correct answer"
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Order number",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="content.lessoncheckboxquestion",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkbox answer option",
                "verbose_name_plural": "Checkbox answer options",
                "ordering": ["order_index"],
                "unique_together": {("question", "order_index")},
            },
        ),
        migrations.AddConstraint(
            model_name="answeroption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_correct", True)),
                fields=("question",),
                name="unique_correct_answer_per_radio_question",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answeroption",
            unique_together={("question", "order_index")},
        ),
    ]
