# Generated by Django 4.2 on 2026-03-15 00:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0003_lessonradioquestion_lessoncheckboxquestion_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answeroption",
            options={
                "ordering": ("order_index",),
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответов",
            },
        ),
        migrations.AlterModelOptions(
            name="checkboxansweroption",
            options={
                "ordering": ("order_index",),
                "verbose_name": "Вариант ответа для чекбокса",
                "verbose_name_plural": "Варианты ответов для чекбоксов",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lessoncheckboxquestion",
            options={
                "ordering": ("order_index",),
                "verbose_name": "Урок с чекбоксами",
                "verbose_name_plural": "Уроки с чекбоксами",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonradioquestion",
            options={
                "ordering": ("order_index",),
                "verbose_name": "Урок с радио-кнопками",
                "verbose_name_plural": "Уроки с радио-кнопками",
            },
        ),
        migrations.AlterModelOptions(
            name="lessontheory",
            options={
                "ordering": ("order_index",),
                "verbose_name": "Теоретический урок",
                "verbose_name_plural": "Теоретические уроки",
            },
        ),
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ("order_index",),
                "verbose_name": "Модуль",
                "verbose_name_plural": "Модули",
            },
        ),
        migrations.AlterModelOptions(
            name="technology",
            options={
                "ordering": ("name",),
                "verbose_name": "Технология",
                "verbose_name_plural": "Технологии",
            },
        ),
        migrations.RemoveConstraint(
            model_name="answeroption",
            name="unique_correct_answer_per_radio_question",
        ),
        migrations.RemoveField(
            model_name="lessoncheckboxquestion",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="lessoncheckboxquestion",
            name="max_correct_answers",
        ),
        migrations.RemoveField(
            model_name="lessoncheckboxquestion",
            name="min_correct_answers",
        ),
        migrations.RemoveField(
            model_name="lessoncheckboxquestion",
            name="partial_points",
        ),
        migrations.RemoveField(
            model_name="lessoncheckboxquestion",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="lessonradioquestion",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="lessonradioquestion",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="is_correct",
            field=models.BooleanField(
                default=False, verbose_name="Правильный ответ"
            ),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="order_index",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="content.lessonradioquestion",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="text",
            field=models.CharField(
                max_length=500, verbose_name="Текст ответа"
            ),
        ),
        migrations.AlterField(
            model_name="checkboxansweroption",
            name="is_correct",
            field=models.BooleanField(
                default=False, verbose_name="Правильный ответ"
            ),
        ),
        migrations.AlterField(
            model_name="checkboxansweroption",
            name="order_index",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterField(
            model_name="checkboxansweroption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="content.lessoncheckboxquestion",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="checkboxansweroption",
            name="text",
            field=models.CharField(
                max_length=500, verbose_name="Текст ответа"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses/images/",
                verbose_name="Обложка курса",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                max_length=200, unique=True, verbose_name="URL адрес"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="technology",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="content.technology",
                verbose_name="Технологии",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                max_length=200, verbose_name="Название курса"
            ),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Пояснение правильных ответов, показываемое после ответа",
                verbose_name="Пояснение",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_checkbox_questions",
                to="content.module",
                verbose_name="Модуль",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="order_index",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="points",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Количество баллов за полностью правильный ответ",
                verbose_name="Баллы",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="question_text",
            field=models.TextField(verbose_name="Текст вопроса"),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="title",
            field=models.CharField(
                max_length=200, verbose_name="Название вопроса"
            ),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Пояснение правильного ответа, показываемое после ответа",
                verbose_name="Пояснение",
            ),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_radio_questions",
                to="content.module",
                verbose_name="Модуль",
            ),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="order_index",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="points",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Количество баллов за правильный ответ",
                verbose_name="Баллы",
            ),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="question_text",
            field=models.TextField(verbose_name="Текст вопроса"),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="title",
            field=models.CharField(
                max_length=200, verbose_name="Название вопроса"
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="content",
            field=models.TextField(verbose_name="Содержание урока"),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_theories",
                to="content.module",
                verbose_name="Модуль",
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="order_index",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="title",
            field=models.CharField(
                max_length=200, verbose_name="Название урока"
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="content.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание модуля"),
        ),
        migrations.AlterField(
            model_name="module",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="module",
            name="order_index",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="title",
            field=models.CharField(
                max_length=200, verbose_name="Название модуля"
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название технологии"
            ),
        ),
    ]
