# Generated by Django 4.2 on 2026-03-18 18:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_lessonradioquestion_lessoncheckboxquestion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Task title"
                    ),
                ),
                ("task_text", models.TextField(verbose_name="Task text")),
                (
                    "submissions_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Submissions count"
                    ),
                ),
                (
                    "solved_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Solved count"
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Order number",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active"),
                ),
                ("correct_code", models.TextField(verbose_name="Correct code")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons_code_tasks",
                        to="content.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code task lesson",
                "verbose_name_plural": "Code task lessons",
                "ordering": ["order_index"],
                "unique_together": {("module", "order_index")},
            },
        ),
        migrations.CreateModel(
            name="CodeTaskTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField(verbose_name="Input data")),
                (
                    "expected_output",
                    models.TextField(verbose_name="Expected output"),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Order number",
                    ),
                ),
                (
                    "code_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="content.codetask",
                        verbose_name="Code task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code task test case",
                "verbose_name_plural": "Code task test cases",
                "ordering": ["order_index"],
                "unique_together": {("code_task", "order_index")},
            },
        ),
    ]
