# Generated by Django 4.2 on 2026-03-17 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_answeroption_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnswerOption",
            new_name="RadioAnswerOption",
        ),
    ]
