# Generated by Django 4.2 on 2026-04-05 09:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_rename_answeroption_radioansweroption"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodingChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Название задачи"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL адрес"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание задачи"),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Подробная инструкция для пользователя",
                        verbose_name="Инструкция по выполнению",
                    ),
                ),
                (
                    "initial_code",
                    models.TextField(
                        blank=True,
                        help_text="Код, который будет показан пользователю как стартовый",
                        verbose_name="Начальный код",
                    ),
                ),
                (
                    "solution_template",
                    models.TextField(
                        help_text="Шаблон с местами для заполнения {{placeholder}}",
                        verbose_name="Шаблон решения",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Начинающий"),
                            ("easy", "Легкий"),
                            ("medium", "Средний"),
                            ("hard", "Сложный"),
                            ("expert", "Эксперт"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Баллы",
                    ),
                ),
                (
                    "time_limit_ms",
                    models.PositiveIntegerField(
                        default=2000,
                        help_text="Максимальное время выполнения решения в миллисекундах",
                        verbose_name="Лимит времени (мс)",
                    ),
                ),
                (
                    "memory_limit_mb",
                    models.PositiveIntegerField(
                        default=256,
                        help_text="Максимальное использование памяти в мегабайтах",
                        verbose_name="Лимит памяти (МБ)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Порядковый номер",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges",
                        to="content.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges",
                        to="content.module",
                        verbose_name="Модуль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ("order_index", "difficulty", "title"),
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_data",
                    models.TextField(
                        help_text="Входные данные для теста",
                        verbose_name="Входные данные",
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(
                        help_text="Ожидаемый вывод программы",
                        verbose_name="Ожидаемый вывод",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Скрытые тесты не показываются пользователю",
                        verbose_name="Скрытый тест",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Порядковый номер",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="content.codingchallenge",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тестовый случай",
                "verbose_name_plural": "Тестовые случаи",
                "ordering": ("order_index",),
                "unique_together": {("challenge", "order_index")},
            },
        ),
        migrations.AddIndex(
            model_name="codingchallenge",
            index=models.Index(
                fields=["course", "order_index"],
                name="content_cod_course__ec0ca1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codingchallenge",
            index=models.Index(
                fields=["module", "order_index"],
                name="content_cod_module__bce5da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codingchallenge",
            index=models.Index(
                fields=["difficulty", "is_active"],
                name="content_cod_difficu_ff7366_idx",
            ),
        ),
    ]
