# Generated by Django 4.2 on 2026-04-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_codingchallenge_testcase_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="codingchallenge",
            unique_together={("module", "order_index")},
        ),
        migrations.RemoveField(
            model_name="codingchallenge",
            name="slug",
        ),
    ]
