# Generated by Django 4.2 on 2026-06-15 01:26

import content.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_lesson_video_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessoncheckboxquestion",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_lessons_checkbox_questions",
                to="content.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="lessonradioquestion",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_lessons_radio_questions",
                to="content.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="lessontheory",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Урок на уровне курса (без модуля и КР)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_lessons_theories",
                to="content.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="codingchallenge",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges",
                to="content.module",
                verbose_name="Модуль",
            ),
        ),
        migrations.AlterField(
            model_name="codingchallenge",
            name="order_index",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Порядок среди всех уроков контейнера (теория, тесты, задачи с кодом)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_checkbox_questions",
                to="content.module",
                verbose_name="Модуль",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="order_index",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Порядок среди всех уроков контейнера (теория, тесты, задачи с кодом)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_radio_questions",
                to="content.module",
                verbose_name="Модуль",
            ),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="order_index",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Порядок среди всех уроков контейнера (теория, тесты, задачи с кодом)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_theories",
                to="content.module",
                verbose_name="Модуль",
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="order_index",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Порядок среди всех уроков контейнера (теория, тесты, задачи с кодом)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Или загрузите MP4/WebM как объяснение",
                null=True,
                upload_to=content.models._lesson_video_upload_to,
                verbose_name="Видеофайл",
            ),
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Порядковый номер в курсе",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=45,
                        help_text="Таймер с момента «Начать»",
                        verbose_name="Длительность (мин)",
                    ),
                ),
                (
                    "navigation_mode",
                    models.CharField(
                        choices=[
                            ("free", "Свободная навигация"),
                            ("linear", "Строго по порядку"),
                        ],
                        default="free",
                        max_length=10,
                        verbose_name="Навигация между заданиями",
                    ),
                ),
                (
                    "tab_policy",
                    models.CharField(
                        choices=[
                            ("log_only", "Только логирование"),
                            ("warn", "Предупреждения"),
                        ],
                        default="log_only",
                        max_length=10,
                        verbose_name="Политика переключения вкладок",
                    ),
                ),
                (
                    "tab_warn_limit",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="После лимита — автосдача с текущими ответами",
                        verbose_name="Лимит предупреждений",
                    ),
                ),
                (
                    "mentor_unlock_required",
                    models.BooleanField(
                        default=False,
                        help_text="Доступ к старту только после одобрения ментора",
                        verbose_name="Нужно разрешение ментора",
                    ),
                ),
                (
                    "pass_score_percent",
                    models.PositiveSmallIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Порог зачёта (%)",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="content.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "prerequisite_modules",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Нужно пройти эти модули перед стартом КР",
                        related_name="required_for_exams",
                        to="content.module",
                        verbose_name="Обязательные модули",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контрольная работа",
                "verbose_name_plural": "Контрольные работы",
                "ordering": ("order_index",),
                "unique_together": {("course", "order_index")},
            },
        ),
        migrations.AddField(
            model_name="codingchallenge",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges",
                to="content.exam",
                verbose_name="Контрольная",
            ),
        ),
        migrations.AddField(
            model_name="lessoncheckboxquestion",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_checkbox_questions",
                to="content.exam",
                verbose_name="Контрольная",
            ),
        ),
        migrations.AddField(
            model_name="lessonradioquestion",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_radio_questions",
                to="content.exam",
                verbose_name="Контрольная",
            ),
        ),
        migrations.AddField(
            model_name="lessontheory",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_theories",
                to="content.exam",
                verbose_name="Контрольная",
            ),
        ),
    ]
