# Generated by Django 4.2 on 2026-06-26 19:54

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_lesson_comment_solution_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codingchallenge",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Пояснение к задаче на вкладке «Задание»",
                verbose_name="Заметка преподавателя",
            ),
        ),
        migrations.AlterField(
            model_name="codingchallenge",
            name="solution_text",
            field=models.TextField(
                blank=True,
                help_text="HTML или текст: код в <pre><code>, картинки, списки — показывается в обсуждении после разблокировки",
                verbose_name="Текст эталонного решения",
            ),
        ),
        migrations.AlterField(
            model_name="codingchallenge",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Видео-разбор в блоке обсуждения",
                null=True,
                upload_to=content.models._lesson_video_upload_to,
                verbose_name="Видеофайл",
            ),
        ),
        migrations.AlterField(
            model_name="codingchallenge",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Видео-разбор в блоке обсуждения",
                max_length=500,
                verbose_name="Ссылка на видео",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Пояснение к заданию на вкладке «Задание»",
                verbose_name="Заметка преподавателя",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="solution_text",
            field=models.TextField(
                blank=True,
                help_text="HTML или текст: код в <pre><code>, картинки, списки — показывается в обсуждении после разблокировки",
                verbose_name="Текст эталонного решения",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Видео-разбор в блоке обсуждения",
                null=True,
                upload_to=content.models._lesson_video_upload_to,
                verbose_name="Видеофайл",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncheckboxquestion",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Видео-разбор в блоке обсуждения",
                max_length=500,
                verbose_name="Ссылка на видео",
            ),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Пояснение к заданию на вкладке «Задание»",
                verbose_name="Заметка преподавателя",
            ),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="solution_text",
            field=models.TextField(
                blank=True,
                help_text="HTML или текст: код в <pre><code>, картинки, списки — показывается в обсуждении после разблокировки",
                verbose_name="Текст эталонного решения",
            ),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Видео-разбор в блоке обсуждения",
                null=True,
                upload_to=content.models._lesson_video_upload_to,
                verbose_name="Видеофайл",
            ),
        ),
        migrations.AlterField(
            model_name="lessonradioquestion",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Видео-разбор в блоке обсуждения",
                max_length=500,
                verbose_name="Ссылка на видео",
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Пояснение от преподавателя на вкладке материала (не путать с комментариями учеников)",
                verbose_name="Заметка преподавателя",
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="solution_text",
            field=models.TextField(
                blank=True,
                help_text="Только для заданий с ответом; у теории не используется",
                verbose_name="Текст эталонного решения",
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Видео к уроку (не эталонное решение)",
                null=True,
                upload_to=content.models._lesson_video_upload_to,
                verbose_name="Видеофайл",
            ),
        ),
        migrations.AlterField(
            model_name="lessontheory",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Видео к уроку (не эталонное решение)",
                max_length=500,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
