# Generated by Django 4.2 on 2026-06-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_alter_codingchallenge_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("-created_at", "-pk"),
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
    ]
