# Generated by Django 4.2 on 2026-08-06 22:40

import content.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_alter_course_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonShortAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Название вопроса"
                    ),
                ),
                (
                    "question_text",
                    models.TextField(verbose_name="Текст вопроса"),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        help_text="Не отдаётся ученику в API",
                        max_length=500,
                        verbose_name="Эталонный ответ",
                    ),
                ),
                (
                    "answer_normalize",
                    models.CharField(
                        choices=[
                            (
                                "strip_casefold",
                                "Trim + пробелы + без регистра",
                            ),
                            ("exact", "Точное совпадение"),
                            ("numeric", "Числовое (зарезервировано)"),
                        ],
                        default="strip_casefold",
                        max_length=32,
                        verbose_name="Нормализация ответа",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Пояснение к заданию на вкладке «Задание»",
                        verbose_name="Заметка преподавателя",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Краткий комментарий после ответа (правильного или неверного)",
                        verbose_name="Пояснение",
                    ),
                ),
                (
                    "solution_text",
                    models.TextField(
                        blank=True,
                        help_text="HTML или текст: показывается в обсуждении после разблокировки",
                        verbose_name="Текст эталонного решения",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Видео-разбор в блоке обсуждения",
                        max_length=500,
                        verbose_name="Ссылка на видео",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Видео-разбор в блоке обсуждения",
                        null=True,
                        upload_to=content.models._lesson_video_upload_to,
                        verbose_name="Видеофайл",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Порядок среди всех уроков контейнера (теория, тесты, задачи с кодом)",
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Порядковый номер",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Количество баллов за правильный ответ",
                        verbose_name="Баллы",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_lessons_short_answers",
                        to="content.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons_short_answers",
                        to="content.exam",
                        verbose_name="Контрольная",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons_short_answers",
                        to="content.module",
                        verbose_name="Модуль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок с кратким ответом",
                "verbose_name_plural": "Уроки с кратким ответом",
                "ordering": ("order_index",),
            },
        ),
        migrations.AddIndex(
            model_name="lessonshortanswer",
            index=models.Index(
                fields=["module", "order_index"],
                name="content_les_module__282fec_idx",
            ),
        ),
    ]
