# Generated by Django 4.2 on 2026-08-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_lesson_short_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="codingchallenge",
            name="assistant_prompt",
            field=models.TextField(
                blank=True,
                help_text="Пусто = базовый шаблон школы. Плейсхолдеры: {{condition}}, {{tests}}, {{title}}, {{course}}, {{code}}.",
                verbose_name="Промпт ИИ (свой)",
            ),
        ),
    ]
