# Generated by Django 4.2 on 2026-08-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_assistant_prompt_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="assistant_prompt",
            field=models.TextField(
                blank=True,
                help_text="Дополнение к общему промпту школы для всех заданий модуля. Плейсхолдеры: {{condition}}, {{tests}}, {{title}}, {{course}}, {{module}}, {{code}}.",
                verbose_name="Промпт ИИ модуля",
            ),
        ),
        migrations.AlterField(
            model_name="codingchallenge",
            name="assistant_prompt",
            field=models.TextField(
                blank=True,
                help_text="Дополнение к общему + модульному промпту. Плейсхолдеры: {{condition}}, {{tests}}, {{title}}, {{course}}, {{module}}, {{code}}.",
                verbose_name="Промпт ИИ (задание)",
            ),
        ),
    ]
