# Generated by Django 5.x on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0022_lesson_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessontheory",
            name="blocks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Порядок урока: текст, картинка, заголовок, важно. "
                    "Пустой список — показываем поле «Содержание»."
                ),
                verbose_name="Блоки теории",
            ),
        ),
    ]
