# Generated by Django 4.2 on 2026-08-11 10:44

from django.db import migrations, models


def seed_assistant_settings(apps, schema_editor):
    AssistantSettings = apps.get_model("mentoring", "AssistantSettings")
    if not AssistantSettings.objects.filter(pk=1).exists():
        AssistantSettings.objects.create(pk=1)


def unseed_assistant_settings(apps, schema_editor):
    AssistantSettings = apps.get_model("mentoring", "AssistantSettings")
    AssistantSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssistantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_prompt",
                    models.TextField(
                        default="Ты помощник ученика онлайн-школы. Отвечай по-русски коротко и чётко.\nНе выдавай полное решение сразу — сначала наводящие подсказки.\n\nКурс: {{course}}\nЗадача: {{title}}\n\nУсловие:\n{{condition}}\n\nТесты:\n{{tests}}\n\nКод ученика (если есть):\n{{code}}\n\nВопрос ученика придёт отдельным сообщением.",
                        help_text="Плейсхолдеры: {{condition}}, {{tests}}, {{title}}, {{course}}, {{code}}. Пустое поле на задаче = этот текст.",
                        verbose_name="Базовый промпт ИИ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки ИИ-помощника",
                "verbose_name_plural": "Настройки ИИ-помощника",
            },
        ),
        migrations.RunPython(
            seed_assistant_settings, unseed_assistant_settings
        ),
    ]
