# Generated by Django 4.2 on 2026-08-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentoring", "0001_assistant_prompt_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistantsettings",
            name="base_prompt",
            field=models.TextField(
                default="Ты помощник ученика онлайн-школы. Отвечай по-русски коротко и чётко.\nНе выдавай полное решение сразу — сначала наводящие подсказки.\n\nКурс: {{course}}\nМодуль: {{module}}\nЗадача: {{title}}\n\nУсловие:\n{{condition}}\n\nТесты:\n{{tests}}\n\nКод ученика (если есть):\n{{code}}\n\nВопрос ученика придёт отдельным сообщением.",
                help_text="Общие правила для всей школы. К ним добавляются промпты модуля и задания (если заданы). Плейсхолдеры: {{condition}}, {{tests}}, {{title}}, {{course}}, {{module}}, {{code}}.",
                verbose_name="Базовый промпт ИИ",
            ),
        ),
    ]
