# Generated by Django 4.2 on 2026-03-17 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0005_rename_answeroption_radioansweroption"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAnswerRadio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        help_text="Был ли ответ правильным",
                        verbose_name="Правильно",
                    ),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Получено баллов"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата ответа"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="content.lessonradioquestion",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "selected_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.radioansweroption",
                        verbose_name="Выбранный ответ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radio_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на radio-вопрос",
                "verbose_name_plural": "Ответы на radio-вопросы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswerCheckBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Были ли все выбранные ответы правильными",
                        verbose_name="Полностью правильно",
                    ),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Получено баллов"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата ответа"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="content.lessoncheckboxquestion",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "selected_answers",
                    models.ManyToManyField(
                        related_name="user_answers",
                        to="content.checkboxansweroption",
                        verbose_name="Выбранные ответы",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkbox_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на checkbox-вопрос",
                "verbose_name_plural": "Ответы на checkbox-вопросы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="useranswerradio",
            index=models.Index(
                fields=["user", "question"],
                name="progress_us_user_id_a3da88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useranswerradio",
            index=models.Index(
                fields=["is_correct"], name="progress_us_is_corr_de12a9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useranswerradio",
            unique_together={("user", "question")},
        ),
        migrations.AddIndex(
            model_name="useranswercheckbox",
            index=models.Index(
                fields=["user", "question"],
                name="progress_us_user_id_0362a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useranswercheckbox",
            index=models.Index(
                fields=["is_correct"], name="progress_us_is_corr_9059b5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useranswercheckbox",
            unique_together={("user", "question")},
        ),
    ]
