# Generated by Django 4.2 on 2026-04-05 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0006_codingchallenge_testcase_and_more"),
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="ID отправки",
                    ),
                ),
                ("code", models.TextField(verbose_name="Код решения")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("running", "Выполняется"),
                            ("completed", "Завершено"),
                            ("error", "Ошибка"),
                            ("timeout", "Превышено время"),
                            ("memory_limit", "Превышена память"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "tests_passed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Пройдено тестов"
                    ),
                ),
                (
                    "total_tests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего тестов"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, verbose_name="Сообщение об ошибке"
                    ),
                ),
                (
                    "test_results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Детальные результаты по каждому тесту",
                        verbose_name="Результаты тестов",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Время отправки",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время завершения"
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="content.codingchallenge",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправка решения",
                "verbose_name_plural": "Отправки решений",
                "ordering": ("-submitted_at",),
            },
        ),
        migrations.AddIndex(
            model_name="codesubmission",
            index=models.Index(
                fields=["user", "challenge", "-submitted_at"],
                name="progress_co_user_id_aad99c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codesubmission",
            index=models.Index(
                fields=["challenge", "status", "-submitted_at"],
                name="progress_co_challen_330300_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codesubmission",
            index=models.Index(
                fields=["user", "status"],
                name="progress_co_user_id_42ea8e_idx",
            ),
        ),
    ]
