# Generated by Django 4.2 on 2026-05-11 02:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0003_rename_submission_public_id_answer_public_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codesubmission",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Публичный идентификатор",
            ),
        ),
    ]
