# Generated by Django 4.2 on 2026-06-15 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_exam_system"),
        ("progress", "0008_seed_achievements"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="achievement",
            new_name="progress_ac_kind_9a0514_idx",
            old_name="progress_ach_kind_0a8f2d_idx",
        ),
        migrations.RenameIndex(
            model_name="userachievement",
            new_name="progress_us_user_id_585c8a_idx",
            old_name="progress_use_user_id_91b4e2_idx",
        ),
        migrations.RenameIndex(
            model_name="userlessontheoryread",
            new_name="progress_us_user_id_42ddb2_idx",
            old_name="progress_use_user_id_3d5c9c_idx",
        ),
        migrations.RenameIndex(
            model_name="userlessontheoryread",
            new_name="progress_us_lesson__3e5a47_idx",
            old_name="progress_use_lesson_i_44c6d9_idx",
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="exam_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="code_submissions",
                to="exams.examattempt",
                verbose_name="Попытка КР",
            ),
        ),
    ]
