# Generated by Django 4.2 on 2026-06-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0011_lessonusercomment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lessonusercomment",
            new_name="progress_le_lesson__006944_idx",
            old_name="progress_le_lesson__a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="lessonusercomment",
            new_name="progress_le_user_id_e7bd89_idx",
            old_name="progress_le_user_id_d4e5f6_idx",
        ),
    ]
