# Generated by Django 4.2 on 2026-08-06 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_lesson_short_answer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "progress",
            "0012_rename_progress_le_lesson__a1b2c3_idx_progress_le_lesson__006944_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonusercomment",
            name="lesson_kind",
            field=models.CharField(
                choices=[
                    ("theory", "Теория"),
                    ("radio", "Radio"),
                    ("checkbox", "Checkbox"),
                    ("coding", "Код"),
                    ("short_answer", "Краткий ответ"),
                ],
                db_index=True,
                max_length=16,
                verbose_name="Тип урока",
            ),
        ),
        migrations.CreateModel(
            name="UserAnswerShort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        max_length=500, verbose_name="Ответ пользователя"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        help_text="Был ли ответ правильным",
                        verbose_name="Правильно",
                    ),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Получено баллов"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата ответа"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="content.lessonshortanswer",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на краткий вопрос",
                "verbose_name_plural": "Ответы на краткие вопросы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="useranswershort",
            index=models.Index(
                fields=["user", "question"],
                name="progress_us_user_id_1632f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useranswershort",
            index=models.Index(
                fields=["is_correct"], name="progress_us_is_corr_87f4b0_idx"
            ),
        ),
    ]
