# Generated by Django 4.2 on 2026-08-12 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_assistant_prompt_four_layers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("progress", "0013_lesson_short_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Выдан"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="content.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сертификат",
                "verbose_name_plural": "Сертификаты",
                "ordering": ("-issued_at",),
            },
        ),
        migrations.AddIndex(
            model_name="coursecertificate",
            index=models.Index(
                fields=["user", "-issued_at"],
                name="progress_co_user_id_3d0a1d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursecertificate",
            unique_together={("user", "course")},
        ),
    ]
