# Generated by Django 4.2 on 2026-06-15 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("progress", "0008_seed_achievements"),
        ("content", "0013_exam_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "В процессе"),
                            ("submitted", "Сдана"),
                            ("expired", "Время вышло"),
                            ("cancelled", "Отменена"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submit_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Сдал сам"),
                            ("timeout", "Истекло время"),
                            ("warn_limit", "Лимит предупреждений"),
                            ("mentor", "Завершил ментор"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("max_score", models.PositiveIntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                (
                    "focus_warn_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="content.exam",
                        verbose_name="Контрольная",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка КР",
                "verbose_name_plural": "Попытки КР",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="ExamFocusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        default="visibility_hidden", max_length=32
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_events",
                        to="exams.examattempt",
                        verbose_name="Попытка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие фокуса",
                "verbose_name_plural": "События фокуса",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ExamAccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "grant_type",
                    models.CharField(
                        choices=[
                            ("unlock", "Открыть доступ"),
                            ("retake", "Разрешить переписать"),
                        ],
                        default="retake",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grants",
                        to="content.exam",
                        verbose_name="Контрольная",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_exam_access",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Выдал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_access_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разрешение на КР",
                "verbose_name_plural": "Разрешения на КР",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ExamAttemptStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "step_kind",
                    models.CharField(
                        choices=[
                            ("theory", "Теория"),
                            ("radio", "Radio"),
                            ("checkbox", "Checkbox"),
                            ("coding", "Код"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content_public_id", models.UUIDField(db_index=True)),
                ("order_index", models.PositiveIntegerField(default=1)),
                ("is_correct", models.BooleanField(default=False)),
                ("points_earned", models.PositiveIntegerField(default=0)),
                ("max_points", models.PositiveIntegerField(default=0)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="exams.examattempt",
                        verbose_name="Попытка",
                    ),
                ),
                (
                    "code_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_attempt_steps",
                        to="progress.codesubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг попытки КР",
                "verbose_name_plural": "Шаги попытки КР",
                "ordering": ("order_index", "updated_at"),
                "unique_together": {
                    ("attempt", "step_kind", "content_public_id")
                },
            },
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["user", "exam", "-started_at"],
                name="exams_exama_user_id_bf4f2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["exam", "status", "-started_at"],
                name="exams_exama_exam_id_f53e4e_idx",
            ),
        ),
    ]
