# Generated by Django 4.2 on 2026-07-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0009_chatmessage_album_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("conference_invite", "Приглашение на созвон"),
                    ("subscription_expiring", "Скоро закончится тариф"),
                ],
                max_length=32,
                verbose_name="Тип",
            ),
        ),
    ]
