# Generated by Django 4.2 on 2026-07-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0010_pro_showcase_reminders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("conference_invite", "Приглашение на созвон"),
                    ("subscription_expiring", "Скоро закончится тариф"),
                    ("mentor_message", "Сообщение от ментора"),
                    ("study_reminder", "Напоминание об учёбе"),
                    ("streak_reminder", "Streak под угрозой"),
                ],
                max_length=32,
                verbose_name="Тип",
            ),
        ),
    ]
