# Generated by Django 4.2 on 2026-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0011_notify_telegram_push_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="source",
            field=models.CharField(
                choices=[("site", "Сайт"), ("vk", "VK")],
                db_index=True,
                default="site",
                max_length=16,
                verbose_name="Источник",
            ),
        ),
    ]
