# Generated by Django 4.2 on 2026-06-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="enrollment",
            new_name="education_e_user_id_c55f32_idx",
            old_name="education_en_user_id_8a1f2d_idx",
        ),
        migrations.RenameIndex(
            model_name="enrollment",
            new_name="education_e_course__79462d_idx",
            old_name="education_en_course__91c4e0_idx",
        ),
    ]
