# Generated by Django 4.2 on 2026-07-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "education",
            "0002_rename_education_en_user_id_8a1f2d_idx_education_e_user_id_c55f32_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="last_study_reminder_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Последнее напоминание об учёбе",
            ),
        ),
    ]
