# Generated by Django 4.2 on 2026-08-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0001_notify_telegram_push_study"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TelegramLinkToken",
        ),
    ]
