# Generated by Django 4.2 on 2025-11-04 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_text",
                    models.TextField(
                        help_text="The original text to be translated.",
                        verbose_name="Source text",
                    ),
                ),
                (
                    "source_lang",
                    models.CharField(
                        help_text="Language of the source text (e.g. 'en', 'ru').",
                        max_length=10,
                        verbose_name="Source language",
                    ),
                ),
                (
                    "target_text",
                    models.TextField(
                        blank=True,
                        help_text="The translated version of the text.",
                        null=True,
                        verbose_name="Translated text",
                    ),
                ),
                (
                    "target_lang",
                    models.CharField(
                        help_text="Language to which the text was translated (e.g. 'en', 'ru').",
                        max_length=10,
                        verbose_name="Target language",
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        blank=True,
                        help_text="Where this translation is used, e.g. 'Specialization.title' or 'Lesson.description'.",
                        max_length=255,
                        null=True,
                        verbose_name="Context",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as approved if the translation was verified by an administrator.",
                        verbose_name="Approved",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who manually edited this translation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last edited by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation",
                "verbose_name_plural": "Translations",
                "ordering": ("-updated_at",),
                "unique_together": {
                    ("source_text", "source_lang", "target_lang", "context")
                },
            },
        ),
    ]
