# Generated by Django 4.2 on 2026-03-17 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="translationmemory",
            options={
                "ordering": ("-updated_at",),
                "verbose_name": "Перевод",
                "verbose_name_plural": "Переводы",
            },
        ),
        migrations.AlterField(
            model_name="translationmemory",
            name="context",
            field=models.CharField(
                blank=True,
                help_text="Где используется этот перевод, например: 'Specialization.title' или 'Lesson.description'.",
                max_length=255,
                null=True,
                verbose_name="Контекст",
            ),
        ),
        migrations.AlterField(
            model_name="translationmemory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="translationmemory",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте как одобрено, если перевод был проверен администратором.",
                verbose_name="Одобрено",
            ),
        ),
        migrations.AlterField(
            model_name="translationmemory",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, который вручную отредактировал этот перевод.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Последний редактор",
            ),
        ),
        migrations.AlterField(
            model_name="translationmemory",
            name="source_lang",
            field=models.CharField(
                help_text="Язык исходного текста (например, 'en', 'ru').",
                max_length=10,
                verbose_name="Исходный язык",
            ),
        ),
        migrations.AlterField(
            model_name="translationmemory",
            name="source_text",
            field=models.TextField(
                help_text="Оригинальный текст для перевода.",
                verbose_name="Исходный текст",
            ),
        ),
        migrations.AlterField(
            model_name="translationmemory",
            name="target_lang",
            field=models.CharField(
                help_text="Язык, на который был переведен текст (например, 'en', 'ru').",
                max_length=10,
                verbose_name="Целевой язык",
            ),
        ),
        migrations.AlterField(
            model_name="translationmemory",
            name="target_text",
            field=models.TextField(
                blank=True,
                help_text="Переведенная версия текста.",
                null=True,
                verbose_name="Переведенный текст",
            ),
        ),
        migrations.AlterField(
            model_name="translationmemory",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления"
            ),
        ),
    ]
