# Generated by Django 4.2 on 2025-10-18 03:38

from django.db import migrations, models
import django.utils.timezone

import users.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Имя пользователя",
                        max_length=255,
                        verbose_name="имя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Фамилия пользователя",
                        max_length=255,
                        verbose_name="фамилия",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Номер телефона пользователя",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Почта пользователя",
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="почта",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("mentor", "Mentor"),
                            ("admin", "Admin"),
                        ],
                        default="student",
                        help_text="Роль пользователя в системе",
                        max_length=50,
                        verbose_name="роль",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Аватар пользователя",
                        null=True,
                        upload_to=users.models.User.upload_to,
                        verbose_name="аватар",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        default="",
                        help_text="Биография пользователя",
                        verbose_name="биография",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата регистрации пользователя",
                        verbose_name="дата регистрации",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Время последнего входа",
                        verbose_name="последний вход",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Активен ли пользователь",
                        verbose_name="активен",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Является ли пользователь сотрудником",
                        verbose_name="сотрудник",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "users",
                "ordering": ["-date_joined", "email"],
            },
        ),
    ]
