# Generated by Django 4.2 on 2025-10-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Биография пользователя",
                verbose_name="биография",
            ),
        ),
    ]
