# Generated by Django 4.2 on 2025-10-27 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0003_alter_user_options_alter_user_avatar_alter_user_bio_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("web", "WEB Development"),
                            ("mobile", "Mobile Development"),
                            ("data", "Data Science"),
                            ("design", "UI/UX Design"),
                            ("marketing", "Digital Marketing"),
                            ("business", "Business"),
                            ("other", "Other"),
                        ],
                        default="web",
                        help_text="Type of specialization",
                        max_length=50,
                        verbose_name="Specialization Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the specialization",
                        max_length=255,
                        verbose_name="Specialization Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the specialization",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this specialization active",
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specialization",
                "verbose_name_plural": "Specializations",
                "db_table": "specializations",
                "ordering": ["type", "title"],
            },
        ),
        migrations.AlterField(
            model_name="mentor",
            name="experience_years",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="How many years experience",
                null=True,
                verbose_name="Experience (in years)",
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary specialization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.specialization",
                verbose_name="Specialization",
            ),
        ),
    ]
