# Generated by Django 4.2 on 2025-10-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0003_alter_user_options_alter_user_avatar_alter_user_bio_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="User biography",
                null=True,
                verbose_name="Biography",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio_ru",
            field=models.TextField(
                blank=True,
                default="",
                help_text="User biography",
                null=True,
                verbose_name="Biography",
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="experience_years",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="How many years experience",
                null=True,
                verbose_name="Experience (in years)",
            ),
        ),
    ]
