# Generated by Django 4.2 on 2025-10-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0004_specialization_alter_mentor_experience_years_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="specialization",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Title of the specialization in english",
                max_length=255,
                null=True,
                verbose_name="English specialization title",
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="title_ru",
            field=models.CharField(
                blank=True,
                help_text="Title of the specialization in russian",
                max_length=255,
                null=True,
                verbose_name="Russian specialization title",
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="translation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Set status of translation",
                max_length=20,
                verbose_name="Translation status",
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="title",
            field=models.CharField(
                help_text="Title of the specialization",
                max_length=255,
                verbose_name="Specialization title",
            ),
        ),
    ]
