# Generated by Django 4.2 on 2025-10-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0005_specialization_title_en_specialization_title_ru_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialization",
            name="type",
            field=models.CharField(
                choices=[
                    ("web", "WEB Development"),
                    ("mobile", "Mobile Development"),
                    ("data", "Data Science"),
                    ("design", "UI/UX Design"),
                    ("marketing", "Digital Marketing"),
                    ("business", "Business"),
                    ("other", "Other"),
                ],
                default="web",
                help_text="Type of specialization",
                max_length=50,
                verbose_name="Specialization type",
            ),
        ),
    ]
