# Generated by Django 4.2 on 2025-11-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_specialization_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialization",
            name="translation_status",
        ),
        migrations.RemoveField(
            model_name="specialization",
            name="updated_at",
        ),
    ]
