# Generated by Django 4.2 on 2025-11-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_specialization_translation_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialization",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="specialization",
            name="title_ru",
        ),
    ]
