# Generated by Django 4.2 on 2025-11-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_specialization_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialization",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the specialization",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the specialization",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="title_en",
            field=models.CharField(
                help_text="Title of the specialization",
                max_length=255,
                null=True,
                verbose_name="Specialization title",
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="title_ru",
            field=models.CharField(
                help_text="Title of the specialization",
                max_length=255,
                null=True,
                verbose_name="Specialization title",
            ),
        ),
    ]
