# Generated by Django 4.2 on 2025-12-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0002_alter_course_options_alter_lessontheory_options_and_more",
        ),
        ("users", "0009_specialization_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="technology",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentors",
                to="content.technology",
                verbose_name="Technologies",
            ),
        ),
    ]
