# Generated by Django 4.2 on 2026-03-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_mentor_technology"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="User biography",
                null=True,
                verbose_name="Biography",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio_ru",
            field=models.TextField(
                blank=True,
                default="",
                help_text="User biography",
                null=True,
                verbose_name="Biography",
            ),
        ),
    ]
