# Generated by Django 4.2 on 2026-03-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_bio_en_user_bio_ru"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio_en",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio_ru",
        ),
    ]
