# Generated by Django 4.2 on 2026-03-17 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_rename_answeroption_radioansweroption"),
        ("users", "0012_remove_user_bio_en_remove_user_bio_ru"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mentor",
            options={
                "verbose_name": "Ментор",
                "verbose_name_plural": "Менторы",
            },
        ),
        migrations.AlterModelOptions(
            name="specialization",
            options={
                "ordering": ["type", "title"],
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализации",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined", "email"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="mentor",
            name="experience_years",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Количество лет опыта",
                null=True,
                verbose_name="Опыт (в годах)",
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                help_text="Основная специализация",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.specialization",
                verbose_name="Специализация",
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="technology",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentors",
                to="content.technology",
                verbose_name="Технологии",
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Подробное описание специализации",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Подробное описание специализации",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text="Подробное описание специализации",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Активна ли эта специализация",
                verbose_name="Активна",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="title",
            field=models.CharField(
                help_text="Название специализации",
                max_length=255,
                verbose_name="Название специализации",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="title_en",
            field=models.CharField(
                help_text="Название специализации",
                max_length=255,
                null=True,
                verbose_name="Название специализации",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="title_ru",
            field=models.CharField(
                help_text="Название специализации",
                max_length=255,
                null=True,
                verbose_name="Название специализации",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="type",
            field=models.CharField(
                choices=[
                    ("web", "WEB-разработка"),
                    ("mobile", "Мобильная разработка"),
                    ("data", "Data Science"),
                    ("design", "UI/UX дизайн"),
                    ("marketing", "Цифровой маркетинг"),
                    ("business", "Бизнес"),
                    ("other", "Другое"),
                ],
                default="web",
                help_text="Тип специализации",
                max_length=50,
                verbose_name="Тип специализации",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Аватар пользователя",
                null=True,
                upload_to=users.models.User.upload_to,
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Биография пользователя",
                verbose_name="Биография",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Дата регистрации пользователя",
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email пользователя",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="Имя пользователя",
                max_length=255,
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Активен ли пользователь",
                verbose_name="Активен",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Является ли пользователь сотрудником",
                verbose_name="Персонал",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Время последнего входа",
                verbose_name="Последний вход",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="Фамилия пользователя",
                max_length=255,
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Номер телефона пользователя",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Студент"),
                    ("mentor", "Ментор"),
                    ("admin", "Администратор"),
                ],
                default="student",
                help_text="Роль пользователя в системе",
                max_length=50,
                verbose_name="Роль",
            ),
        ),
    ]
