# Generated by Django 4.2 on 2026-07-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_uuid_public_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID чата Telegram для уведомлений",
                null=True,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_linked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Telegram привязан"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Telegram username",
            ),
        ),
    ]
