# Generated by Django 4.2 on 2026-07-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_demote_mentor_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Доступ к Django /admin. Только для role=admin; менторы работают в /mentor.",
                verbose_name="Персонал",
            ),
        ),
    ]
