# Generated by Django 4.2 on 2026-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="telegram_linked_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="telegram_username",
        ),
        migrations.AddField(
            model_name="user",
            name="vk_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Идентификатор VK (OAuth и сообщения сообщества)",
                null=True,
                unique=True,
                verbose_name="VK ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="vk_messages_allowed",
            field=models.BooleanField(
                default=False,
                help_text="Пользователь разрешил сообщения от сообщества",
                verbose_name="VK: сообщения разрешены",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="yandex_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор Яндекс ID",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Yandex ID",
            ),
        ),
    ]
