# Generated by Django 4.2 on 2026-08-09 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_vk_oauth_drop_telegram"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="assigned_mentor",
            field=models.ForeignKey(
                blank=True,
                help_text="Ментор ученика. Если пусто — admin или ментор курса.",
                limit_choices_to={
                    "is_active": True,
                    "role__in": ("mentor", "admin"),
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Назначенный ментор",
            ),
        ),
    ]
