# Generated by Django 4.2 on 2026-08-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_student_assigned_mentor"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Пользователь подтвердил почту кодом из письма",
                verbose_name="Email подтверждён",
            ),
        ),
    ]
